name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - staging

jobs:
  frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm test -- --coverage

      - name: Upload frontend coverage report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: frontend/coverage

  backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Set up MongoDB environment variables
        run: |
          echo "MONGO_URI_TEST=${{ secrets.MONGO_URI_TEST }}" >> $GITHUB_ENV
          echo "PORT=5000" >> $GITHUB_ENV

      - name: Verify MongoDB URI
        run: |
          echo "MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}"

      - name: Run backend tests
        run: |
          cd backend
          npm test -- --coverage

      - name: Upload backend coverage report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: backend/coverage
