name: Frontend CI/CD

on:
  push:
    branches:
      - main
      - feature
  pull_request:
    branches:
      - main
      - staging

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify Node.js version
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: app/komponentko/frontend
        run: |
          if [ ! -f "package-lock.json" ]; then
            echo "Error: package-lock.json not found!"
            exit 1
          fi
          npm ci  # Use `npm ci` for a clean install based on the lock file

      # Step 4: Run tests
      - name: Run tests
        working-directory: app/komponentko/frontend
        run: npm test

      # Step 5: Build the frontend
      - name: Build the frontend
        working-directory: app/komponentko/frontend
        run: npm run build
